version: '3'

services:
  # db:
  #   image: postgres
  django:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh ./django_graphql/docker-entrypoint.sh
    volumes:
      - .:/django_graphql
    ports:
      - "8000:8000"
    # depends_on:
    #   - db